name: Clean Isometric Graph

on:
  # Runs at 00:00 every day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Iso Calendar
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token (automatically provided)
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # This filename is where the image will be saved
          filename: iso-calendar.svg
          
          # "base: header" keeps it minimal. "base: """ removes everything but the plugin.
          base: ""
          
          # Enable ONLY the isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
